const tempRecipe = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 20,
  gaps: "no",
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 19,
  healthScore: 2,
  creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
  license: "CC BY 3.0",
  sourceName: "Foodista",
  pricePerServing: 100.71,
  extendedIngredients: [
    {
      id: 20081,
      aisle: "Baking",
      image: "flour.png",
      consistency: "SOLID",
      name: "flour",
      nameClean: "wheat flour",
      original: "1 cup all-purpose flour",
      originalName: "all-purpose flour",
      amount: 1,
      unit: "cup",
      meta: ["all-purpose"],
      measures: {
        us: {
          amount: 1,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 125,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 19335,
      aisle: "Baking",
      image: "sugar-in-bowl.png",
      consistency: "SOLID",
      name: "sugar",
      nameClean: "sugar",
      original: "1 cup sugar",
      originalName: "sugar",
      amount: 1,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 1,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 200,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 18369,
      aisle: "Baking",
      image: "white-powder.jpg",
      consistency: "SOLID",
      name: "baking powder",
      nameClean: "baking powder",
      original: "3 teaspoons Tbs.+ 1 baking powder",
      originalName: "Tbs.+ 1 baking powder",
      amount: 3,
      unit: "teaspoons",
      meta: [],
      measures: {
        us: {
          amount: 3,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 3,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 2047,
      aisle: "Spices and Seasonings",
      image: "salt.jpg",
      consistency: "SOLID",
      name: "salt",
      nameClean: "table salt",
      original: "2 teaspoons salt",
      originalName: "salt",
      amount: 2,
      unit: "teaspoons",
      meta: [],
      measures: {
        us: {
          amount: 2,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 2,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 1032009,
      aisle: "Spices and Seasonings",
      image: "red-pepper-flakes.jpg",
      consistency: "SOLID",
      name: "pepper flakes",
      nameClean: "red pepper flakes",
      original: "1/2 teaspoon red pepper flakes",
      originalName: "red pepper flakes",
      amount: 0.5,
      unit: "teaspoon",
      meta: ["red"],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 1002014,
      aisle: "Spices and Seasonings",
      image: "ground-cumin.jpg",
      consistency: "SOLID",
      name: "cumin",
      nameClean: "cumin",
      original: "1 teaspoon cumin",
      originalName: "cumin",
      amount: 1,
      unit: "teaspoon",
      meta: [],
      measures: {
        us: {
          amount: 1,
          unitShort: "tsp",
          unitLong: "teaspoon",
        },
        metric: {
          amount: 1,
          unitShort: "tsp",
          unitLong: "teaspoon",
        },
      },
    },
    {
      id: 11165,
      aisle: "Spices and Seasonings",
      image: "cilantro.png",
      consistency: "SOLID",
      name: "coriander",
      nameClean: "cilantro",
      original: "1 teaspoon coriander",
      originalName: "coriander",
      amount: 1,
      unit: "teaspoon",
      meta: [],
      measures: {
        us: {
          amount: 1,
          unitShort: "tsp",
          unitLong: "teaspoon",
        },
        metric: {
          amount: 1,
          unitShort: "tsp",
          unitLong: "teaspoon",
        },
      },
    },
    {
      id: 1123,
      aisle: "Milk, Eggs, Other Dairy",
      image: "egg.png",
      consistency: "SOLID",
      name: "eggs",
      nameClean: "egg",
      original: "6 large eggs",
      originalName: "eggs",
      amount: 6,
      unit: "large",
      meta: [],
      measures: {
        us: {
          amount: 6,
          unitShort: "large",
          unitLong: "larges",
        },
        metric: {
          amount: 6,
          unitShort: "large",
          unitLong: "larges",
        },
      },
    },
    {
      id: 1001,
      aisle: "Milk, Eggs, Other Dairy",
      image: "butter-sliced.jpg",
      consistency: "SOLID",
      name: "butter",
      nameClean: "butter",
      original: "1 stick melted butter (½ cup)",
      originalName: "stick melted butter",
      amount: 0.5,
      unit: "cup",
      meta: ["melted"],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 113.5,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 1053,
      aisle: "Milk, Eggs, Other Dairy",
      image: "fluid-cream.jpg",
      consistency: "LIQUID",
      name: "heavy cream",
      nameClean: "cream",
      original: "2 cups heavy cream",
      originalName: "heavy cream",
      amount: 2,
      unit: "cups",
      meta: [],
      measures: {
        us: {
          amount: 2,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 476,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 11174,
      aisle: "Canned and Jarred",
      image: "creamed-corn.png",
      consistency: "SOLID",
      name: "creamed corn",
      nameClean: "creamed corn",
      original: "14 oz. can of creamed corn",
      originalName: "creamed corn",
      amount: 14,
      unit: "oz",
      meta: ["canned"],
      measures: {
        us: {
          amount: 14,
          unitShort: "oz",
          unitLong: "ounces",
        },
        metric: {
          amount: 396.893,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 10011333,
      aisle: "Produce",
      image: "poblano-peppers.jpg",
      consistency: "SOLID",
      name: "poblano peppers",
      nameClean: "poblano pepper",
      original: "2 fresh poblano peppers, seeded and diced",
      originalName: "fresh poblano peppers, seeded and diced",
      amount: 2,
      unit: "",
      meta: ["fresh", "diced", "seeded"],
      measures: {
        us: {
          amount: 2,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 2,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 11913,
      aisle: "Frozen",
      image: "corn.png",
      consistency: "SOLID",
      name: "corn",
      nameClean: "frozen corn",
      original: "1 cup fresh or frozen corn",
      originalName: "fresh or frozen corn",
      amount: 1,
      unit: "cup",
      meta: ["fresh"],
      measures: {
        us: {
          amount: 1,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 165,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
  ],
  id: 641223,
  title: "Damn Good Corn Pudding ~from 12 Bones Smokehouse",
  readyInMinutes: 45,
  servings: 10,
  sourceUrl:
    "https://www.foodista.com/recipe/6P65X54W/damn-good-corn-pudding-from-12-bones-smokehouse",
  image: "https://img.spoonacular.com/recipes/641223-556x370.jpg",
  imageType: "jpg",
  taste: {
    sweetness: 80.6,
    saltiness: 38.5,
    sourness: 4.12,
    bitterness: 2.12,
    savoriness: 19.77,
    fattiness: 100,
    spiciness: 297500,
  },
  summary:
    'Damn Good Corn Pudding ~from 12 Bones Smokehouse is a side dish that serves 10. One serving contains \u003Cb\u003E460 calories\u003C/b\u003E, \u003Cb\u003E8g of protein\u003C/b\u003E, and \u003Cb\u003E30g of fat\u003C/b\u003E. For \u003Cb\u003E$1.01 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 11%\u003C/b\u003E of your daily requirements of vitamins and minerals. 19 people were glad they tried this recipe. It is brought to you by Foodista. Head to the store and pick up heavy cream, butter, corn, and a few other things to make it today. From preparation to the plate, this recipe takes approximately \u003Cb\u003E45 minutes\u003C/b\u003E. With a spoonacular \u003Cb\u003Escore of 33%\u003C/b\u003E, this dish is rather bad. Try \u003Ca href="https://spoonacular.com/recipes/damn-good-corn-pudding-from-12-bones-smokehouse-551670"\u003EDamn Good Corn Pudding ~from 12 Bones Smokehouse\u003C/a\u003E, \u003Ca href="https://spoonacular.com/recipes/12-bones-corn-pudding-1014369"\u003E12 Bones Corn Pudding\u003C/a\u003E, and \u003Ca href="https://spoonacular.com/recipes/damn-good-blt-pasta-salad-1503607"\u003EDamn Good BLT Pasta Salad\u003C/a\u003E for similar recipes.',
  cuisines: [],
  dishTypes: ["side dish"],
  diets: [],
  occasions: [],
  winePairing: {
    pairedWines: [],
    pairingText: "",
    productMatches: [],
  },
  instructions:
    "Preheat the oven to 350 degrees F.\nMix all the dry ingredients together in a bowl.\nPour the eggs, butter, cream and creamed corn in an electric mixer.\nMix well and add the poblanos and corn. Slowly add the flour mixture and mix until just combined. It should resemble cake batter.\nGrease a large 11 X 15 rimmed baking dish. (You could use two smaller dishes.) Pour the pudding mixture into the pan and place it in the oven. Lightly tent the pan with foil.\nBake for 1 hour, until the center is just set. (30-40 minutes for smaller pans) You may want to take the foil off the last 10-15 minutes so the top will be golden.\nServes 1, or if youre in a sharing mood 8-10.",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Preheat the oven to 350 degrees F.",
          ingredients: [],
          equipment: [
            {
              id: 404784,
              name: "oven",
              localizedName: "oven",
              image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
              temperature: {
                number: 350,
                unit: "Fahrenheit",
              },
            },
          ],
        },
        {
          number: 2,
          step: "Mix all the dry ingredients together in a bowl.",
          ingredients: [],
          equipment: [
            {
              id: 404783,
              name: "bowl",
              localizedName: "bowl",
              image: "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
            },
          ],
        },
        {
          number: 3,
          step: "Pour the eggs, butter, cream and creamed corn in an electric mixer.",
          ingredients: [
            {
              id: 11174,
              name: "creamed corn",
              localizedName: "creamed corn",
              image:
                "https://spoonacular.com/cdn/ingredients_100x100/creamed-corn.png",
            },
            {
              id: 1001,
              name: "butter",
              localizedName: "butter",
              image:
                "https://spoonacular.com/cdn/ingredients_100x100/butter-sliced.jpg",
            },
            {
              id: 1053,
              name: "cream",
              localizedName: "cream",
              image:
                "https://spoonacular.com/cdn/ingredients_100x100/fluid-cream.jpg",
            },
            {
              id: 1123,
              name: "egg",
              localizedName: "egg",
              image: "https://spoonacular.com/cdn/ingredients_100x100/egg.png",
            },
          ],
          equipment: [
            {
              id: 404628,
              name: "hand mixer",
              localizedName: "hand mixer",
              image:
                "https://spoonacular.com/cdn/equipment_100x100/hand-mixer.png",
            },
          ],
        },
        {
          number: 4,
          step: "Mix well and add the poblanos and corn. Slowly add the flour mixture and mix until just combined. It should resemble cake batter.",
          ingredients: [
            {
              id: 10011333,
              name: "poblano pepper",
              localizedName: "poblano pepper",
              image:
                "https://spoonacular.com/cdn/ingredients_100x100/poblano-peppers.jpg",
            },
            {
              id: 20081,
              name: "all purpose flour",
              localizedName: "all purpose flour",
              image:
                "https://spoonacular.com/cdn/ingredients_100x100/flour.png",
            },
            {
              id: 11168,
              name: "corn",
              localizedName: "corn",
              image: "https://spoonacular.com/cdn/ingredients_100x100/corn.png",
            },
          ],
          equipment: [],
        },
        {
          number: 5,
          step: "Grease a large 11 X 15 rimmed baking dish. (You could use two smaller dishes.)",
          ingredients: [],
          equipment: [
            {
              id: 404646,
              name: "baking pan",
              localizedName: "baking pan",
              image:
                "https://spoonacular.com/cdn/equipment_100x100/roasting-pan.jpg",
            },
          ],
        },
        {
          number: 6,
          step: "Pour the pudding mixture into the pan and place it in the oven. Lightly tent the pan with foil.",
          ingredients: [],
          equipment: [
            {
              id: 404765,
              name: "aluminum foil",
              localizedName: "aluminum foil",
              image:
                "https://spoonacular.com/cdn/equipment_100x100/aluminum-foil.png",
            },
            {
              id: 404784,
              name: "oven",
              localizedName: "oven",
              image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
            },
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "https://spoonacular.com/cdn/equipment_100x100/pan.png",
            },
          ],
        },
        {
          number: 7,
          step: "Bake for 1 hour, until the center is just set. (30-40 minutes for smaller pans) You may want to take the foil off the last 10-15 minutes so the top will be golden.",
          ingredients: [],
          equipment: [
            {
              id: 404784,
              name: "oven",
              localizedName: "oven",
              image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
            },
            {
              id: 404765,
              name: "aluminum foil",
              localizedName: "aluminum foil",
              image:
                "https://spoonacular.com/cdn/equipment_100x100/aluminum-foil.png",
            },
          ],
          length: {
            number: 115,
            unit: "minutes",
          },
        },
        {
          number: 8,
          step: "Serves 1, or if youre in a sharing mood 8-10.",
          ingredients: [],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularScore: 37.7049827575684,
  spoonacularSourceUrl:
    "https://spoonacular.com/damn-good-corn-pudding-from-12-bones-smokehouse-641223",
};

export { tempRecipe };
